spring.application.name=foodhelp-backend
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/ServidorRecetas
spring.datasource.username=postgres
spring.datasource.password=recetario
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.file.name=logs/foodhelp-registros.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

// en esta carpeta va todas las configuaciones de conexion con postgre
